name: 'Portainer Stack Deploy'
description: 'Deploy or update Docker Swarm stacks on Portainer using Git repository or string content. Supports API Key/Username+Password auth and access control.'
author: 'robert843'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/robert843/github-action-portainer:v0.0.14'
  args:
    - --portainer-host=${{ inputs.portainer-host }}
    - --stack-name=${{ inputs.stack-name }}
    - --endpoint-name=${{ inputs.endpoint-name }}
    - --deployment-method=${{ inputs.deployment-method }}
    - --prune=${{ inputs.prune }}
    - --pull-image=${{ inputs.pull-image }}
    - --access=${{ inputs.access }}
    - --use-https=${{ inputs.use-https }}
    - ${{ inputs.api-key && format('--api-key={0}', inputs.api-key) || '' }}
    - ${{ inputs.username && format('--username={0}', inputs.username) || '' }}
    - ${{ inputs.password && format('--password={0}', inputs.password) || '' }}
    - ${{ inputs.repository-url && format('--repository-url={0}', inputs.repository-url) || '' }}
    - ${{ inputs.repository-reference && format('--repository-reference={0}', inputs.repository-reference) || '' }}
    - ${{ inputs.repository-username && format('--repository-username={0}', inputs.repository-username) || '' }}
    - ${{ inputs.repository-password && format('--repository-password={0}', inputs.repository-password) || '' }}
    - ${{ inputs.compose-file-path && format('--compose-file-path={0}', inputs.compose-file-path) || '' }}
    - ${{ inputs.stack-file && format('--stack-file={0}', inputs.stack-file) || '' }}
    - ${{ inputs.environment-variables && format('--environment-variables={0}', inputs.environment-variables) || '' }}
    - ${{ inputs.auto-update && format('--auto-update={0}', inputs.auto-update) || '' }}
    - ${{ inputs.auto-update-interval && format('--auto-update-interval={0}', inputs.auto-update-interval) || '' }}
    - ${{ inputs.teams && format('--teams={0}', inputs.teams) || '' }}

inputs:
  # --- CONNECTION / AUTH ---
  portainer-host:
    description: 'Portainer host (e.g. your.portainer.io). Include protocol if not using HTTPS.'
    required: true
  use-https:
    description: 'Use HTTPS to connect to Portainer.'
    required: false
    default: 'true'
  api-key:
    description: 'Portainer API Key (X-API-Key). If not provided, username/password will be used.'
    required: false
  username:
    description: 'Portainer username (if api-key is not used).'
    required: false
  password:
    description: 'Portainer password (if api-key is not used).'
    required: false

  # --- STACK & DEPLOYMENT ---
  stack-name:
    description: 'Stack name to create or update.'
    required: true
  endpoint-name:
    description: 'Endpoint name to deploy to (will be resolved to ID).'
    required: true
    default: 'local'
  deployment-method:
    description: 'Deployment method: repository | string.'
    required: true
    default: 'repository'

  # --- REPOSITORY MODE ---
  repository-url:
    description: 'Git repository URL (for repository mode).'
    required: false
  repository-reference:
    description: 'Repository ref (branch/tag/commit). Default: refs/heads/main.'
    required: false
    default: 'refs/heads/main'
  repository-username:
    description: 'Username for private repository access (if required).'
    required: false
  repository-password:
    description: 'Password or PAT for private repository access (if required).'
    required: false
  compose-file-path:
    description: 'Compose file path in repository (for repository mode).'
    required: false
    default: 'docker-compose.yml'

  # --- STRING MODE ---
  stack-file:
    description: 'Local stack file path to read content from (for string mode).'
    required: false

  # --- OPTIONS ---
  environment-variables:
    description: 'JSON array of environment variables, e.g. [{"name":"FOO","value":"bar"}].'
    required: false
  prune:
    description: 'Set to true to prune unused services on update.'
    required: false
    default: 'false'
  pull-image:
    description: 'Set to true to pull latest images on update.'
    required: false
    default: 'true'
  auto-update:
    description: 'Enable auto-update for repository stacks (true|false).'
    required: false
    default: 'false'
  auto-update-interval:
    description: 'Auto-update interval (e.g. 5m). Only relevant if auto-update is true.'
    required: false
    default: '5m'

  # --- ACCESS CONTROL ---
  access:
    description: 'Access mode: public | teams | admin.'
    required: false
    default: 'admin'
  teams:
    description: 'Comma-separated teams names (used when access=teams).'
    required: false